### ISSUE TITLE
Suggestions for improvements on `sdfx`

### ISSUE THREAD

**Issue by soypat** [Yeicor/sdfx-ui#12]
Hello! I'm currently [rewriting](https://github.com/soypat/sdf) `sdfx` and am looking for developer/user opinions on the current implementation of `sdfx`. I'd like to know if `sdfx-ui` developers had any hitches or ideas on things they would have liked to change about `sdfx`!

So far I've had a x2 performance improvement in the rewrite (before bringing in multicore processing!)

**Comment by yeicor** [comment]
Nice work improving performance! I can see that a rewrite was needed because of your design differences with the original `sdfx` library.

I would only suggest for now that you keep the SDF3 interface as close as possible to the original (and maybe provide a wrapper to convert between them on a separate package), so that users can mix and match the surfaces and features contributed to both projects.

I will leave this open so that other users can comment on your project.
