### ISSUE TITLE
Future plans & visions

### ISSUE THREAD

**Issue by dumblob** [Yeicor/sdfx-ui#2]
The answer in https://github.com/Yeicor/sdfx-ui/issues/1 sparked my interest and I'd like to know whether you have any plans to extend the sdfx-ui to something as advanced as https://github.com/CadQuery/cadquery ?

Or otherwise what are the plans & visions?

**Comment by yeicor** [comment]
This could be expanded into a full editor like CadQuery or OpenSCAD. However, in my opinion, the source code should be kept separate from the UI: it would be reinventing the wheel and interfering with Go's infrastructure. It is better to let each user use their favorite IDE and integrate with the extremely simple API offered by this library in the way they choose. It should just provide a window that quickly renders the designed SDF for fast development, following the [KISS principle](https://en.wikipedia.org/wiki/KISS_principle).

The UI has a lot of room for improvement. For example, the bounds (AABBs) of each object could be drawn in order to show the user where they are, even if you are subtracting an SDF and not actually colliding with the previous SDF so no modification is visible. Another possible improvement is selecting which SDFs to temporarily enable or disable in a tree or even trace clicks to detect which SDFs were clicked and link that back to the source code. All these improvements require different levels of [reflection](https://pkg.go.dev/reflect) or even sampling/profiling to analyze the input SDF hierarchy.

That said, I am currently focusing on other projects and won't be working on this for a while. Nevertheless, I am open to hearing any specific ideas on how to improve the UI, and reviewing and helping with pull requests.

**Comment by dumblob** [comment]
Yes, you guessed it right - my main motivation is to significantly increase interactivity - i.e. all the seeing object boundaries, clicking objects + jumping right into the code place, etc.

Let's see if I find some time to test the current behavior in detail (at least compared to CadQuery as I don't consider OpenSCAD to be a good example - rather the opposite).

**Comment by gedw99** [comment]
I was thinking about how to remove the reflection so that the systems interactive performance is as high as possible.

Here is the idea .. 

We maintain a dom like xml description of the SDF structure . It’s just elements with kv properties like any xml tree. This can be kept on disk with a memory cache.

When a user interacts with the gui and mutation is an event that is sent to the backend . The backend handler then updates the gui via a command handler and also the dom  via the kv structure of the xml dom.

With the gui when a user clicks on an object we want to show a property grid so they can edit the kv property values . This is gotten from the xml dom .


This is overly simplistic but you get the general idea . 

I build something like this ages ago and it was very extensible because you catered for users that only want to interact via the gui as well as users that wanted to also edit the xml dom file.

If you want the gui to update when the xml dom is hand edited you need to maintain a diff so you can fire the op events to the gui command handler . 

The other advantage is that the dom files work with git of course. 

There is another thing you can do which is to use flatbuffers to create a schema . The ops send from the backend tonthe print end are flatbuffers and is very fast . You can take all the possible add ops and model them as flatbuffers and then just generate your types

**Comment by yeicor** [comment]
I am not so sure that reflection will become a performance problem for this use case: the reflection-based tree is only computed once per surface change (sub-SDFs can be used directly without reflection after that) and should be small. For example, the complex example added at examples/cylinder_head has less than 100 nodes in the reflection-based tree and computes them only once in half a millisecond. Furthermore, you would also need to perform a reflection-based inspection for each run for the idea you propose, even if its just to check that nothing changed.

I don't think the XML interface has advantages (code can also be committed to git, the GUI already updates on code edits and, as explained above, it would also require reflection), and it's most clear disadvantage is that it would be restricting the user to a limited set of SDF implementations. One of the best things about SDFX is the possibility to write your own SDF implementation to easily try new ideas, and we shouldn't limit this. The current approach should work with any correct SDF implementation, even if it was not previously known by this library.

**Comment by gedw99** [comment]
thanks @Yeicor for the in review. I am glad to hear the perf is not affected badly.  

I personally might extend it to support a Markdown basis though. I want to be able to change the properties at runtime, and a DOM like structure is one way do it.
